name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Garanta que está apontando para a branch correta, pode ser 'main' em alguns casos

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'  # Especifique a versão do Node.js que deseja usar

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages  # Branch destino para o deploy
        folder: build  # Pasta que contém os arquivos de build para deploy
